<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tour;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Schema;

class TourSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Tour::truncate();
        Schema::enableForeignKeyConstraints();
        
        $tours = [
            [
                'name' => 'The Great Migration Luxury Safari (8 Days)',
                'description' => 'A premium 8-day Great Migration safari through Serengeti and Ngorongoro, designed for high-end international travelers seeking luxury lodges, peak wildlife viewing, and iconic river crossing moments.',
                'location' => 'Serengeti National Park, Ngorongoro Crater & Arusha, Tanzania',
                'duration_days' => 8,
                'base_price' => 4500.00,
                'international_price_min' => 4500.00,
                'international_price_max' => 9000.00,
                'best_season' => 'June – October',
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'serengeti-national-park', 'label' => 'Serengeti National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'ngorongoro-crater', 'label' => 'Ngorongoro Crater'],
                    ['entity_type' => 'destination', 'entity_ref' => 'arusha', 'label' => 'Arusha'],
                ],
                'target_markets' => ['USA', 'UK', 'Germany', 'France'],
                'interactive_features' => [
                    'Migration movement calendar',
                    'Wildlife probability indicator (lion 85%, leopard 60%)',
                    'Luxury lodge comparison slider',
                    'Balloon safari toggle (+$550)',
                ],
                'addons' => ['Balloon safari (+$550)'],
                'conversion_triggers' => ['Only 6 river crossing dates available this season!'],
                'featured' => true,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766042771/8-Days-Tanzania-holiday-Wildebeest-migration-1536x1018_gyndkw.jpg',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046204/Mara-River-3-1536x1024_qflu8o.webp',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046143/9-Days-Safari-vacation-Tanzania-Wildebeest-migration-1536x962_m0drtg.webp'
                ],
                'inclusions' => ['Luxury Tented Camps', 'Private 4x4 Safari Vehicle', 'Unlimited Game Drives', 'All Park & Crater Fees', 'Airport Transfers'],
                'exclusions' => ['International Flights', 'Tanzania Entry Visa', 'Tips for Guides', 'Travel Insurance'],
            ],
            [
                'name' => 'Kilimanjaro Summit Challenge (7 Days Machame Route)',
                'description' => 'A 7-day summit attempt via the Machame Route, built for adventure-minded travelers who want a challenge with strong acclimatization pacing and clear performance insights.',
                'location' => 'Mount Kilimanjaro, Tanzania',
                'duration_days' => 7,
                'base_price' => 2100.00,
                'international_price_min' => 2100.00,
                'international_price_max' => 3500.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'mount-kilimanjaro', 'label' => 'Mount Kilimanjaro'],
                ],
                'target_markets' => ['Adventure travelers (Age 20–45)'],
                'interactive_features' => [
                    'Route difficulty meter',
                    'Oxygen level tracker simulation',
                    'Summit success rate stats',
                    'Fitness self-assessment quiz',
                ],
                'addons' => ['Zanzibar recovery extension'],
                'conversion_triggers' => [],
                'featured' => true,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766324377/7-Days-Mount-Kilimanjaro-Climb-Lemosho-Route-2.webp.bv.webp',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046350/kilimanjaro-climbing_bvcs7p.jpg',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766324492/lemosho-route-packages-2-1-600x275.jpg.bv_vbxuaq.webp'
                ],
                'inclusions' => ['All Mountain Fees', 'Certified Lead Guides', 'Nutritious Mountain Meals', 'Tents & Sleeping Mats', 'Oxygen Cylinders for Safety'],
                'exclusions' => ['Mountain Trekking Gear', 'Sleeping Bags', 'Tips for Porters & Guides', 'Extra Hotel Nights'],
            ],
            [
                'name' => 'Zanzibar Luxury Honeymoon Escape (6 Days)',
                'description' => 'A romantic 6-day Zanzibar escape combining beach relaxation in Nungwi with culture and history in Stone Town—perfect for newlyweds seeking privacy and upgrades.',
                'location' => 'Nungwi Beach & Stone Town, Zanzibar',
                'duration_days' => 6,
                'base_price' => 2800.00,
                'international_price_min' => 2800.00,
                'international_price_max' => 6000.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'nungwi-beach', 'label' => 'Nungwi Beach'],
                    ['entity_type' => 'destination', 'entity_ref' => 'stone-town', 'label' => 'Stone Town'],
                ],
                'target_markets' => ['Couples / Newlyweds'],
                'interactive_features' => [
                    'Romantic dinner selector',
                    'Private yacht sunset cruise option',
                    'Honeymoon room upgrade toggle',
                    'Personalized love message on arrival',
                ],
                'addons' => ['Private yacht sunset cruise option', 'Honeymoon room upgrade'],
                'conversion_triggers' => [],
                'featured' => true,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046173/beautiful-tropical-beach-sea-ocean-with-coconut-palm-tree-umbrella-chair-blue-sky_ezrdjs.jpg',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046169/closeup-shot-beautiful-bird-sitting-pick-up_enaih2.jpg'
                ],
                'inclusions' => ['Luxury Beach Resort', 'Airport Transfers', 'Private Experiences'],
                'exclusions' => ['Flights to Zanzibar', 'Personal Expenses', 'Tips'],
            ],
            [
                'name' => 'Northern Circuit Budget Safari (5 Days)',
                'description' => 'A value-focused 5-day safari for budget travelers visiting Tarangire, Lake Manyara, and Ngorongoro—built around flexible group joining and lodging style selection.',
                'location' => 'Tarangire, Lake Manyara & Ngorongoro, Tanzania',
                'duration_days' => 5,
                'base_price' => 1200.00,
                'international_price_min' => 1200.00,
                'international_price_max' => 1800.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'tarangire-national-park', 'label' => 'Tarangire National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'lake-manyara-national-park', 'label' => 'Lake Manyara National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'ngorongoro-crater', 'label' => 'Ngorongoro Crater'],
                ],
                'target_markets' => ['Backpackers / Students'],
                'interactive_features' => [
                    'Group join option',
                    'Camping vs Lodge switch',
                    'Student discount calculator',
                ],
                'addons' => ['Camping option', 'Lodge upgrade'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046154/Angata-Tarangire-2-1-1536x863_amthnm.jpg',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046228/tower-giraffes-gathered-around-bushes-open-woodlan_fsgqe3.jpg'
                ],
                'inclusions' => ['Shared Safari Vehicle', 'Park Fees', 'Meals'],
                'exclusions' => ['Tips', 'Personal Expenses', 'Alcohol'],
            ],
            [
                'name' => 'Southern Tanzania Wild Experience (7 Days)',
                'description' => 'A 7-day safari for repeat travelers focusing on the southern circuit—Nyerere (Selous) and Ruaha—known for wide-open wilderness and fewer crowds.',
                'location' => 'Nyerere National Park & Ruaha National Park, Tanzania',
                'duration_days' => 7,
                'base_price' => 3200.00,
                'international_price_min' => 3200.00,
                'international_price_max' => 5500.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'nyerere-national-park', 'label' => 'Nyerere National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'ruaha-national-park', 'label' => 'Ruaha National Park'],
                ],
                'target_markets' => ['Repeat safari travelers'],
                'interactive_features' => [
                    'Boat safari selection',
                    'Walking safari add-on',
                    'Low tourist density badge',
                ],
                'addons' => ['Boat safari selection', 'Walking safari add-on'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766324498/beautiful-waterfall-streaming-into-river-surrounded-by-greens_dgyhld.jpg',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766324502/closeup-shot-elephants-standing-near-lake-sunset_set5ic.jpg'
                ],
                'inclusions' => ['Game Drives', 'Safari Guide', 'Accommodation', 'Meals'],
                'exclusions' => ['Airfare', 'Tips', 'Laundry'],
            ],
            [
                'name' => 'Tanzania Family Adventure (8 Days)',
                'description' => 'An 8-day family-friendly itinerary mixing classic safari in Serengeti with Zanzibar city time—optimized for kids activities, child pricing, and family room planning.',
                'location' => 'Serengeti National Park & Zanzibar City, Tanzania',
                'duration_days' => 8,
                'base_price' => 3000.00,
                'international_price_min' => 3000.00,
                'international_price_max' => 6000.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'serengeti-national-park', 'label' => 'Serengeti National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'zanzibar-city', 'label' => 'Zanzibar City'],
                ],
                'target_markets' => ['Families with kids'],
                'interactive_features' => [
                    'Kids-friendly activity filter',
                    'Child pricing auto-calculation',
                    'Family room configuration tool',
                ],
                'addons' => [],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766042771/8-Days-Tanzania-holiday-Wildebeest-migration-1536x1018_gyndkw.jpg',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046173/beautiful-tropical-beach-sea-ocean-with-coconut-palm-tree-umbrella-chair-blue-sky_ezrdjs.jpg'
                ],
                'inclusions' => ['Family-friendly lodging', 'Private guide', 'Transfers'],
                'exclusions' => ['Tips', 'Personal expenses'],
            ],
            [
                'name' => 'Tanzania Photography Safari (9 Days)',
                'description' => 'A 9-day photography-first safari focusing on light, timing, and positioning across Serengeti and Ngorongoro—ideal for pros looking for heat maps, golden hours, and specialist support.',
                'location' => 'Serengeti National Park & Ngorongoro Crater, Tanzania',
                'duration_days' => 9,
                'base_price' => 4000.00,
                'international_price_min' => 4000.00,
                'international_price_max' => 7500.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'serengeti-national-park', 'label' => 'Serengeti National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'ngorongoro-crater', 'label' => 'Ngorongoro Crater'],
                ],
                'target_markets' => ['Professional photographers'],
                'interactive_features' => [
                    'Golden hour schedule',
                    'Wildlife sighting heat map',
                    'Photography guide add-on',
                    '4x4 open roof vehicle upgrade',
                ],
                'addons' => ['Photography guide add-on', '4x4 open roof vehicle upgrade'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046228/tower-giraffes-gathered-around-bushes-open-woodlan_fsgqe3.jpg',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046204/Mara-River-3-1536x1024_qflu8o.webp'
                ],
                'inclusions' => ['Private 4x4 Safari Vehicle', 'Expert Guide', 'Park Fees'],
                'exclusions' => ['Flights', 'Tips', 'Personal insurance'],
            ],
            [
                'name' => 'Cultural & Community Impact Tour (6 Days)',
                'description' => 'A 6-day responsible travel itinerary focused on culture and community outcomes across Arusha, Maasai villages, and local school projects—built for NGOs and impact-minded travelers.',
                'location' => 'Arusha & Community Projects, Tanzania',
                'duration_days' => 6,
                'base_price' => 1800.00,
                'international_price_min' => 1800.00,
                'international_price_max' => 3200.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'arusha', 'label' => 'Arusha'],
                    ['entity_type' => 'destination', 'entity_ref' => 'maasai-villages', 'label' => 'Maasai villages'],
                    ['entity_type' => 'destination', 'entity_ref' => 'local-schools-projects', 'label' => 'Local schools projects'],
                ],
                'target_markets' => ['Responsible tourists / NGOs'],
                'interactive_features' => [
                    'Community impact tracker',
                    'Donation integration option',
                    'Cultural workshop selector',
                ],
                'addons' => ['Donation integration option'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046195/hadzabe_qgukhh.jpg',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766324498/man-with-dreads-representing-rastafari-movement_jmcqny.jpg'
                ],
                'inclusions' => ['Local guides', 'Project visits', 'Cultural sessions'],
                'exclusions' => ['Personal donations', 'Tips'],
            ],
            [
                'name' => 'Luxury Fly-In Safari (5 Days)',
                'description' => 'A 5-day VIP fly-in experience into Serengeti and Ngorongoro—built around private charter flexibility, premium arrival handling, and luxury add-ons.',
                'location' => 'Serengeti National Park & Ngorongoro Crater, Tanzania',
                'duration_days' => 5,
                'base_price' => 6000.00,
                'international_price_min' => 6000.00,
                'international_price_max' => 12000.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'serengeti-national-park', 'label' => 'Serengeti National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'ngorongoro-crater', 'label' => 'Ngorongoro Crater'],
                ],
                'target_markets' => ['VIP travelers'],
                'interactive_features' => [
                    'Private charter option',
                    'Helicopter scenic flight',
                    'VIP airport meet & greet',
                    'Champagne bush breakfast toggle',
                ],
                'addons' => ['Private charter option', 'Helicopter scenic flight', 'VIP airport meet & greet', 'Champagne bush breakfast toggle'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046204/Mara-River-3-1536x1024_qflu8o.webp',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766042771/8-Days-Tanzania-holiday-Wildebeest-migration-1536x1018_gyndkw.jpg'
                ],
                'inclusions' => ['Luxury lodge/tented camp', 'Private guide', 'Premium transfers'],
                'exclusions' => ['International flights', 'Tips', 'Travel insurance'],
            ],
            [
                'name' => 'Tanzania Ultimate Combo (12–14 Days)',
                'description' => 'A bucket-list combo that merges Kilimanjaro, classic safari, and Zanzibar beach time—built around a unified timeline, multi-route map, and flexible payments.',
                'location' => 'Kilimanjaro + Serengeti + Zanzibar, Tanzania',
                'duration_days' => 12,
                'base_price' => 6500.00,
                'international_price_min' => 6500.00,
                'international_price_max' => 15000.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'mount-kilimanjaro', 'label' => 'Mount Kilimanjaro'],
                    ['entity_type' => 'destination', 'entity_ref' => 'serengeti-national-park', 'label' => 'Serengeti National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'nungwi-beach', 'label' => 'Nungwi Beach'],
                ],
                'target_markets' => ['International bucket-list travelers'],
                'interactive_features' => [
                    'Full trip timeline visualization',
                    'Multi-destination route map',
                    'Payment installment plan option',
                    'Travel insurance integration',
                    'VIP concierge upgrade',
                ],
                'addons' => ['VIP concierge upgrade', 'Payment installment plan option', 'Travel insurance integration'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046350/kilimanjaro-climbing_bvcs7p.jpg',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766042771/7-DAYS-SAFARI-TANZANIA--1536x1024_d9kzfh.webp',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046173/beautiful-tropical-beach-sea-ocean-with-coconut-palm-tree-umbrella-chair-blue-sky_ezrdjs.jpg'
                ],
                'inclusions' => ['Safari segment', 'Kilimanjaro segment', 'Zanzibar segment'],
                'exclusions' => ['International flights', 'Visa fees', 'Tips'],
            ],
            [
                'name' => 'Serengeti Classic Big Five Safari (7 Days)',
                'description' => 'A classic 7-day safari experience across the Northern Circuit with extended Serengeti time for Big Five sightings and diverse landscapes.',
                'location' => 'Serengeti & Ngorongoro, Tanzania',
                'duration_days' => 7,
                'base_price' => 2400.00,
                'international_price_min' => 2400.00,
                'international_price_max' => 4200.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'serengeti-national-park', 'label' => 'Serengeti National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'ngorongoro-crater', 'label' => 'Ngorongoro Crater'],
                ],
                'target_markets' => ['General safari travelers'],
                'interactive_features' => [],
                'addons' => ['Private vehicle upgrade'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766042771/7-DAYS-SAFARI-TANZANIA--1536x1024_d9kzfh.webp',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046228/tower-giraffes-gathered-around-bushes-open-woodlan_fsgqe3.jpg'
                ],
                'inclusions' => ['Safari vehicle', 'Guide', 'Park fees', 'Meals'],
                'exclusions' => ['International flights', 'Tips', 'Insurance'],
            ],
            [
                'name' => 'Tarangire Elephant Encounter (2 Days)',
                'description' => 'A short and affordable Tarangire safari focused on elephant herds, baobab scenery, and easy logistics from Arusha.',
                'location' => 'Tarangire National Park, Tanzania',
                'duration_days' => 2,
                'base_price' => 780.00,
                'international_price_min' => 780.00,
                'international_price_max' => 1200.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'tarangire-national-park', 'label' => 'Tarangire National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'arusha', 'label' => 'Arusha'],
                ],
                'target_markets' => ['Weekend safari travelers'],
                'interactive_features' => [],
                'addons' => ['Lodge upgrade'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046154/Angata-Tarangire-2-1-1536x863_amthnm.jpg',
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766324502/closeup-shot-elephants-standing-near-lake-sunset_set5ic.jpg'
                ],
                'inclusions' => ['Park fees', 'Guide', 'Meals'],
                'exclusions' => ['Tips', 'Personal expenses'],
            ],
            [
                'name' => 'Ngorongoro Crater Day Trip (1 Day)',
                'description' => 'A full-day descent into the Ngorongoro Crater for high-density wildlife viewing and iconic scenery.',
                'location' => 'Ngorongoro Crater, Tanzania',
                'duration_days' => 1,
                'base_price' => 490.00,
                'international_price_min' => 490.00,
                'international_price_max' => 850.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'ngorongoro-crater', 'label' => 'Ngorongoro Crater'],
                ],
                'target_markets' => ['Short-stay travelers'],
                'interactive_features' => [],
                'addons' => [],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046204/Mara-River-3-1536x1024_qflu8o.webp'
                ],
                'inclusions' => ['Crater fees', 'Guide', 'Lunch box'],
                'exclusions' => ['Tips', 'Drinks'],
            ],
            [
                'name' => 'Lake Manyara Scenic Safari (2 Days)',
                'description' => 'Explore Lake Manyara’s lush groundwater forest, birdlife, and classic safari scenes in a compact itinerary.',
                'location' => 'Lake Manyara National Park, Tanzania',
                'duration_days' => 2,
                'base_price' => 720.00,
                'international_price_min' => 720.00,
                'international_price_max' => 1150.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'lake-manyara-national-park', 'label' => 'Lake Manyara National Park'],
                ],
                'target_markets' => ['Nature lovers'],
                'interactive_features' => [],
                'addons' => [],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046169/closeup-shot-beautiful-bird-sitting-pick-up_enaih2.jpg'
                ],
                'inclusions' => ['Park fees', 'Guide', 'Meals'],
                'exclusions' => ['Tips', 'Alcohol'],
            ],
            [
                'name' => 'Ruaha Wilderness Expedition (6 Days)',
                'description' => 'A deeper southern circuit safari featuring vast landscapes, predators, and a wild feel in Ruaha National Park.',
                'location' => 'Ruaha National Park, Tanzania',
                'duration_days' => 6,
                'base_price' => 3400.00,
                'international_price_min' => 3400.00,
                'international_price_max' => 5200.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'ruaha-national-park', 'label' => 'Ruaha National Park'],
                ],
                'target_markets' => ['Repeat safari travelers'],
                'interactive_features' => ['Low tourist density badge'],
                'addons' => ['Walking safari add-on'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766324502/closeup-shot-elephants-standing-near-lake-sunset_set5ic.jpg'
                ],
                'inclusions' => ['Accommodation', 'Meals', 'Guided game drives'],
                'exclusions' => ['Airfare', 'Tips'],
            ],
            [
                'name' => 'Nyerere (Selous) River & Boat Safari (5 Days)',
                'description' => 'A southern circuit itinerary combining classic game drives with signature boat safaris on the Rufiji River system.',
                'location' => 'Nyerere National Park, Tanzania',
                'duration_days' => 5,
                'base_price' => 2600.00,
                'international_price_min' => 2600.00,
                'international_price_max' => 4300.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'nyerere-national-park', 'label' => 'Nyerere National Park'],
                ],
                'target_markets' => ['Wildlife enthusiasts'],
                'interactive_features' => ['Boat safari selection'],
                'addons' => ['Boat safari selection'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766324498/beautiful-waterfall-streaming-into-river-surrounded-by-greens_dgyhld.jpg'
                ],
                'inclusions' => ['Boat safari', 'Game drives', 'Meals'],
                'exclusions' => ['Airfare', 'Tips'],
            ],
            [
                'name' => 'Hadzabe & Eyasi Cultural Experience (2 Days)',
                'description' => 'A short cultural tour visiting the Hadzabe community in the Lake Eyasi area, with guided interpretation and respectful engagement.',
                'location' => 'Lake Eyasi, Tanzania',
                'duration_days' => 2,
                'base_price' => 680.00,
                'international_price_min' => 680.00,
                'international_price_max' => 1200.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'lake-eyasi', 'label' => 'Lake Eyasi'],
                ],
                'target_markets' => ['Responsible tourists'],
                'interactive_features' => ['Cultural workshop selector'],
                'addons' => [],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046195/hadzabe_qgukhh.jpg'
                ],
                'inclusions' => ['Local guide', 'Community fees'],
                'exclusions' => ['Tips', 'Personal gifts'],
            ],
            [
                'name' => 'Zanzibar Spice & Beach Break (4 Days)',
                'description' => 'A quick Zanzibar escape with beach time and a spice experience, perfect as a post-safari add-on.',
                'location' => 'Stone Town & Nungwi, Zanzibar',
                'duration_days' => 4,
                'base_price' => 1250.00,
                'international_price_min' => 1250.00,
                'international_price_max' => 2400.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'stone-town', 'label' => 'Stone Town'],
                    ['entity_type' => 'destination', 'entity_ref' => 'nungwi-beach', 'label' => 'Nungwi Beach'],
                ],
                'target_markets' => ['Beach lovers'],
                'interactive_features' => [],
                'addons' => ['Private transfer upgrade'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046173/beautiful-tropical-beach-sea-ocean-with-coconut-palm-tree-umbrella-chair-blue-sky_ezrdjs.jpg'
                ],
                'inclusions' => ['Resort stay', 'Transfers'],
                'exclusions' => ['Flights', 'Tips'],
            ],
            [
                'name' => 'Katavi Secret Safari (7 Days)',
                'description' => 'A remote safari for true wilderness seekers. Katavi offers dramatic wildlife concentrations with very low tourist density.',
                'location' => 'Katavi National Park, Tanzania',
                'duration_days' => 7,
                'base_price' => 5200.00,
                'international_price_min' => 5200.00,
                'international_price_max' => 9000.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'katavi-national-park', 'label' => 'Katavi National Park'],
                ],
                'target_markets' => ['VIP travelers', 'Repeat safari travelers'],
                'interactive_features' => ['Low tourist density badge'],
                'addons' => ['Fly-in option'],
                'conversion_triggers' => ['Limited camps available in Katavi each season.'],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766262419/beautiful-zebra-wild.jpg'
                ],
                'inclusions' => ['Luxury camping', 'Private guide'],
                'exclusions' => ['International flights', 'Tips'],
            ],
            [
                'name' => 'Serengeti Express Safari (5 Days)',
                'description' => 'A fast-paced 5-day Serengeti-focused itinerary designed for travelers with limited time but big wildlife expectations.',
                'location' => 'Serengeti National Park, Tanzania',
                'duration_days' => 5,
                'base_price' => 2100.00,
                'international_price_min' => 2100.00,
                'international_price_max' => 3600.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'serengeti-national-park', 'label' => 'Serengeti National Park'],
                ],
                'target_markets' => ['International travelers'],
                'interactive_features' => [],
                'addons' => ['Private vehicle upgrade'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046228/tower-giraffes-gathered-around-bushes-open-woodlan_fsgqe3.jpg'
                ],
                'inclusions' => ['Park fees', 'Guide', 'Meals', 'Accommodation'],
                'exclusions' => ['Flights', 'Tips', 'Insurance'],
            ],
            [
                'name' => 'Northern Circuit Highlights (5 Days)',
                'description' => 'A 5-day safari combining Tarangire, Lake Manyara, and Ngorongoro for a high-coverage Northern Circuit overview.',
                'location' => 'Tarangire, Lake Manyara & Ngorongoro, Tanzania',
                'duration_days' => 5,
                'base_price' => 1650.00,
                'international_price_min' => 1650.00,
                'international_price_max' => 2600.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'tarangire-national-park', 'label' => 'Tarangire National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'lake-manyara-national-park', 'label' => 'Lake Manyara National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'ngorongoro-crater', 'label' => 'Ngorongoro Crater'],
                ],
                'target_markets' => ['First-time safari travelers'],
                'interactive_features' => ['Camping vs Lodge switch'],
                'addons' => ['Lodge upgrade'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046154/Angata-Tarangire-2-1-1536x863_amthnm.jpg'
                ],
                'inclusions' => ['Park fees', 'Guide', 'Meals', 'Accommodation'],
                'exclusions' => ['Tips', 'Personal expenses'],
            ],
            [
                'name' => 'Serengeti & Ngorongoro Classic (5 Days)',
                'description' => 'A balanced 5-day itinerary combining Serengeti plains and the Ngorongoro Crater for maximum wildlife variety.',
                'location' => 'Serengeti & Ngorongoro, Tanzania',
                'duration_days' => 5,
                'base_price' => 1950.00,
                'international_price_min' => 1950.00,
                'international_price_max' => 3200.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'serengeti-national-park', 'label' => 'Serengeti National Park'],
                    ['entity_type' => 'destination', 'entity_ref' => 'ngorongoro-crater', 'label' => 'Ngorongoro Crater'],
                ],
                'target_markets' => ['General safari travelers'],
                'interactive_features' => [],
                'addons' => ['Hot air balloon add-on'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046204/Mara-River-3-1536x1024_qflu8o.webp'
                ],
                'inclusions' => ['Park fees', 'Guide', 'Meals', 'Accommodation'],
                'exclusions' => ['Flights', 'Tips'],
            ],
            [
                'name' => 'Zanzibar Beach & Stone Town (5 Days)',
                'description' => 'A 5-day Zanzibar holiday mixing historic Stone Town exploration with beach relaxation in Nungwi.',
                'location' => 'Stone Town & Nungwi, Zanzibar',
                'duration_days' => 5,
                'base_price' => 1800.00,
                'international_price_min' => 1800.00,
                'international_price_max' => 3800.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'stone-town', 'label' => 'Stone Town'],
                    ['entity_type' => 'destination', 'entity_ref' => 'nungwi-beach', 'label' => 'Nungwi Beach'],
                ],
                'target_markets' => ['Couples', 'Beach travelers'],
                'interactive_features' => ['Romantic dinner selector'],
                'addons' => ['Private yacht sunset cruise option'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046173/beautiful-tropical-beach-sea-ocean-with-coconut-palm-tree-umbrella-chair-blue-sky_ezrdjs.jpg'
                ],
                'inclusions' => ['Resort stay', 'Transfers'],
                'exclusions' => ['Flights', 'Personal expenses'],
            ],
            [
                'name' => 'Arusha & Tarangire Quick Safari (2 Days)',
                'description' => 'A short 2-day safari departing from Arusha to explore Tarangire’s elephants and baobab landscapes.',
                'location' => 'Arusha & Tarangire, Tanzania',
                'duration_days' => 2,
                'base_price' => 650.00,
                'international_price_min' => 650.00,
                'international_price_max' => 1050.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'arusha', 'label' => 'Arusha'],
                    ['entity_type' => 'destination', 'entity_ref' => 'tarangire-national-park', 'label' => 'Tarangire National Park'],
                ],
                'target_markets' => ['Short-stay travelers'],
                'interactive_features' => [],
                'addons' => ['Lodge upgrade'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046154/Angata-Tarangire-2-1-1536x863_amthnm.jpg'
                ],
                'inclusions' => ['Park fees', 'Guide', 'Meals'],
                'exclusions' => ['Tips', 'Drinks'],
            ],
            [
                'name' => 'Lake Manyara & Karatu Getaway (2 Days)',
                'description' => 'A relaxed 2-day trip to Lake Manyara with an overnight near Karatu for comfortable pacing.',
                'location' => 'Lake Manyara & Karatu, Tanzania',
                'duration_days' => 2,
                'base_price' => 690.00,
                'international_price_min' => 690.00,
                'international_price_max' => 1150.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'lake-manyara-national-park', 'label' => 'Lake Manyara National Park'],
                ],
                'target_markets' => ['Nature lovers'],
                'interactive_features' => [],
                'addons' => ['Lodge upgrade'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046169/closeup-shot-beautiful-bird-sitting-pick-up_enaih2.jpg'
                ],
                'inclusions' => ['Park fees', 'Guide', 'Meals'],
                'exclusions' => ['Tips', 'Personal expenses'],
            ],
            [
                'name' => 'Ngorongoro Crater & Highlands (2 Days)',
                'description' => 'A 2-day trip with a crater descent plus time on the Ngorongoro highlands for scenic viewpoints.',
                'location' => 'Ngorongoro, Tanzania',
                'duration_days' => 2,
                'base_price' => 920.00,
                'international_price_min' => 920.00,
                'international_price_max' => 1500.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'ngorongoro-crater', 'label' => 'Ngorongoro Crater'],
                ],
                'target_markets' => ['Short-stay travelers'],
                'interactive_features' => [],
                'addons' => [],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046204/Mara-River-3-1536x1024_qflu8o.webp'
                ],
                'inclusions' => ['Crater fees', 'Guide', 'Meals'],
                'exclusions' => ['Tips', 'Drinks'],
            ],
            [
                'name' => 'Zanzibar Couples Escape (2 Days)',
                'description' => 'A quick 2-day Zanzibar couples retreat for travelers who want a short beach break and a touch of romance.',
                'location' => 'Nungwi, Zanzibar',
                'duration_days' => 2,
                'base_price' => 980.00,
                'international_price_min' => 980.00,
                'international_price_max' => 1800.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'nungwi-beach', 'label' => 'Nungwi Beach'],
                ],
                'target_markets' => ['Couples'],
                'interactive_features' => ['Romantic dinner selector'],
                'addons' => ['Honeymoon room upgrade'],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766046173/beautiful-tropical-beach-sea-ocean-with-coconut-palm-tree-umbrella-chair-blue-sky_ezrdjs.jpg'
                ],
                'inclusions' => ['Resort stay', 'Transfers'],
                'exclusions' => ['Flights', 'Personal expenses'],
            ],
            [
                'name' => 'Mkomazi Rhino Sanctuary (2 Days)',
                'description' => 'A conservation-focused 2-day tour featuring the Mkomazi Rhino Sanctuary and ranger-led experiences.',
                'location' => 'Mkomazi, Tanzania',
                'duration_days' => 2,
                'base_price' => 820.00,
                'international_price_min' => 820.00,
                'international_price_max' => 1400.00,
                'best_season' => null,
                'package_destinations' => [
                    ['entity_type' => 'destination', 'entity_ref' => 'mkomazi', 'label' => 'Mkomazi Rhino Sanctuary'],
                ],
                'target_markets' => ['Conservation-minded travelers'],
                'interactive_features' => [],
                'addons' => [],
                'conversion_triggers' => [],
                'featured' => false,
                'status' => 'active',
                'images' => [
                    'https://res.cloudinary.com/dmqdm8gfk/image/upload/v1766262419/beautiful-zebra-wild.jpg'
                ],
                'inclusions' => ['Park fees', 'Ranger guide', 'Meals'],
                'exclusions' => ['Tips', 'Personal expenses'],
            ],
        ];

        foreach ($tours as $t) {
            $t['slug'] = Str::slug($t['name']);
            Tour::create($t);
        }
    }
}
